"""initial schema

Static baseline of the schema as it stood after development-plan step 2. The
SQLAlchemy models remain the single source of truth for the *current* schema;
this revision is an explicit, frozen snapshot so later revisions can add or
alter tables incrementally with ``alembic revision --autogenerate`` without the
baseline re-creating everything from live metadata.

Revision ID: 0001
Revises:
Create Date: 2026-07-20

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('stat_team_id', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_team_id')
    )
    op.create_table('competitions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('fantasy_tournament_id', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_tournament_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('trigger_type', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('tournament_slug', sa.Text(), nullable=False),
    sa.Column('requested_season_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ingestion_runs_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('stat_player_id', sa.Text(), nullable=True),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_player_id')
    )
    op.create_table('raw_api_responses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_name', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_hash', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'operation_name', 'response_hash', name='raw_api_responses_run_operation_hash_key')
    )
    op.create_table('seasons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('fantasy_season_id', sa.Text(), nullable=False),
    sa.Column('stat_season_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_season_id'),
    sa.UniqueConstraint('stat_season_id')
    )
    op.create_table('fantasy_tours',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('fantasy_tour_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finishes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfers_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfers_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_transfers', sa.Integer(), nullable=True),
    sa.Column('max_same_team_players', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'fantasy_tour_id', name='fantasy_tours_season_tour_key')
    )
    op.create_table('season_clubs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('fantasy_team_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'club_id', name='season_clubs_season_club_key'),
    sa.UniqueConstraint('season_id', 'fantasy_team_id', name='season_clubs_season_fantasy_team_key')
    )
    op.create_table('season_rules',
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('rules_html', sa.Text(), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_players', sa.Integer(), nullable=False),
    sa.Column('starting_players', sa.Integer(), nullable=False),
    sa.Column('full_roster_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starting_roster_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('club_season_stats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('season_club_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('matches_won', sa.Integer(), nullable=False),
    sa.Column('matches_drawn', sa.Integer(), nullable=False),
    sa.Column('matches_lost', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('home_matches', sa.Integer(), nullable=True),
    sa.Column('home_goals_scored', sa.Integer(), nullable=True),
    sa.Column('home_goals_conceded', sa.Integer(), nullable=True),
    sa.Column('away_matches', sa.Integer(), nullable=True),
    sa.Column('away_goals_scored', sa.Integer(), nullable=True),
    sa.Column('away_goals_conceded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['season_club_id'], ['season_clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_club_id', 'ingestion_run_id', name='club_season_stats_club_run_key')
    )
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('tour_id', sa.BigInteger(), nullable=True),
    sa.Column('stat_match_id', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_club_id', sa.BigInteger(), nullable=False),
    sa.Column('away_club_id', sa.BigInteger(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['home_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['fantasy_tours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_match_id')
    )
    op.create_index('matches_season_scheduled_idx', 'matches', ['season_id', 'scheduled_at'], unique=False)
    op.create_table('player_seasons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('fantasy_player_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('current_season_club_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("role IN ('GOALKEEPER', 'DEFENDER', 'MIDFIELDER', 'FORWARD')", name='player_seasons_role_check'),
    sa.ForeignKeyConstraint(['current_season_club_id'], ['season_clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'fantasy_player_id', name='player_seasons_season_fantasy_player_key'),
    sa.UniqueConstraint('season_id', 'player_id', name='player_seasons_season_player_key')
    )
    op.create_table('club_match_stats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('opponent_club_id', sa.BigInteger(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('provider_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'club_id', name='club_match_stats_match_club_key')
    )
    op.create_table('fantasy_player_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('player_season_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('season_club_id', sa.BigInteger(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('availability_status', sa.Text(), nullable=False),
    sa.Column('status_description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('selected_by', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('season_score', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_tour_score', sa.Integer(), nullable=True),
    sa.Column('top_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_club_id'], ['season_clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_season_id', 'ingestion_run_id', name='fantasy_player_snapshots_player_run_key')
    )
    op.create_index('fantasy_player_snapshots_latest_idx', 'fantasy_player_snapshots', ['player_season_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_table('player_match_stats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('player_season_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('tour_id', sa.BigInteger(), nullable=False),
    sa.Column('season_club_id', sa.BigInteger(), nullable=True),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('penalties_missed', sa.Integer(), nullable=False),
    sa.Column('penalties_post', sa.Integer(), nullable=False),
    sa.Column('penalties_target', sa.Integer(), nullable=False),
    sa.Column('penalties_saved', sa.Integer(), nullable=False),
    sa.Column('field_minutes', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('penalty_goals_conceded', sa.Integer(), nullable=False),
    sa.Column('penalties_faced', sa.Integer(), nullable=False),
    sa.Column('penalty_conceded', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('ball_recoveries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_club_id'], ['season_clubs.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['fantasy_tours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_season_id', 'match_id', name='player_match_stats_player_match_key')
    )
    op.create_index('player_match_stats_player_idx', 'player_match_stats', ['player_season_id', 'match_id'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('player_season_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('penalties_missed', sa.Integer(), nullable=False),
    sa.Column('penalties_post', sa.Integer(), nullable=False),
    sa.Column('penalties_target', sa.Integer(), nullable=False),
    sa.Column('penalties_saved', sa.Integer(), nullable=False),
    sa.Column('field_minutes', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('penalty_goals_conceded', sa.Integer(), nullable=False),
    sa.Column('penalties_faced', sa.Integer(), nullable=False),
    sa.Column('penalty_conceded', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('ball_recoveries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_season_id', 'ingestion_run_id', name='player_season_stats_player_run_key')
    )
    op.create_table('fantasy_point_details',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('player_match_stat_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_match_stat_id'], ['player_match_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_match_stat_id', 'ordinal', name='fantasy_point_details_stat_ordinal_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fantasy_point_details')
    op.drop_table('player_season_stats')
    op.drop_index('player_match_stats_player_idx', table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index('fantasy_player_snapshots_latest_idx', table_name='fantasy_player_snapshots')
    op.drop_table('fantasy_player_snapshots')
    op.drop_table('club_match_stats')
    op.drop_table('player_seasons')
    op.drop_index('matches_season_scheduled_idx', table_name='matches')
    op.drop_table('matches')
    op.drop_table('club_season_stats')
    op.drop_table('season_rules')
    op.drop_table('season_clubs')
    op.drop_table('fantasy_tours')
    op.drop_table('seasons')
    op.drop_table('raw_api_responses')
    op.drop_table('players')
    op.drop_table('ingestion_runs')
    op.drop_table('competitions')
    op.drop_table('clubs')
    # ### end Alembic commands ###
