"""data quality issues and active snapshot

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-21 10:43:56.079707

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_issues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=True),
    sa.Column('check_name', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_ref', sa.Text(), nullable=True),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('blocking', 'warning')", name='data_quality_issues_severity_check'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('data_quality_issues_run_idx', 'data_quality_issues', ['ingestion_run_id'], unique=False)
    op.create_index('data_quality_issues_run_severity_idx', 'data_quality_issues', ['ingestion_run_id', 'severity'], unique=False)
    op.add_column('ingestion_runs', sa.Column('season_id', sa.BigInteger(), nullable=True))
    op.add_column('ingestion_runs', sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('ingestion_runs', sa.Column('quality_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ingestion_runs_active_season_idx', 'ingestion_runs', ['season_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_foreign_key(
        'ingestion_runs_season_id_fkey',
        'ingestion_runs',
        'seasons',
        ['season_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ingestion_runs_season_id_fkey', 'ingestion_runs', type_='foreignkey'
    )
    op.drop_index('ingestion_runs_active_season_idx', table_name='ingestion_runs', postgresql_where=sa.text('is_active'))
    op.drop_column('ingestion_runs', 'quality_checked_at')
    op.drop_column('ingestion_runs', 'is_active')
    op.drop_column('ingestion_runs', 'season_id')
    op.drop_index('data_quality_issues_run_severity_idx', table_name='data_quality_issues')
    op.drop_index('data_quality_issues_run_idx', table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    # ### end Alembic commands ###
