"""ingestion jobs table

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-21 11:09:06.054853

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('trigger_type', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('tournament_slug', sa.Text(), nullable=False),
    sa.Column('requested_season_id', sa.Text(), nullable=True),
    sa.Column('requested_season_name', sa.Text(), nullable=True),
    sa.Column('use_current_season', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ingestion_jobs_status_check'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ingestion_jobs_active_tournament_idx', 'ingestion_jobs', ['tournament_slug'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ingestion_jobs_active_tournament_idx', table_name='ingestion_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
