"""player forecasts table

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-21 14:06:21.061856

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_forecasts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=True),
    sa.Column('tour_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_season_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('feature_version', sa.Text(), nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=True),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_points', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('uncertainty', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('p_appearance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['fantasy_tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'tour_id', 'model_name', 'model_version', 'player_season_id', 'match_id', name='player_forecasts_run_model_player_match_key')
    )
    op.create_index('player_forecasts_run_tour_model_idx', 'player_forecasts', ['ingestion_run_id', 'tour_id', 'model_name', 'model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('player_forecasts_run_tour_model_idx', table_name='player_forecasts')
    op.drop_table('player_forecasts')
    # ### end Alembic commands ###
